Hotfix / Improve feed performance
andreidumitru11/golfr_backend pull request #2
Opened 2024-07-29 10:38 UTC by andreidumitru11

Fix: [#1](https://github.com/AACraiu/golfr_backend/issues/1) Improve scores feed performance

**Changes**

We load the users in two queries  instead of n + 1. ( we would write a query that selects all the users that are in the vector of ids obtained from scores, but the  "includes" method does that under the hood )

**Before**
<img width="997" alt="Screenshot 2024-07-29 at 13 55 09" src="https://github.com/user-attachments/assets/d7ee4b1b-0ef5-4722-8786-b9accb182966">

**After**
<img width="998" alt="Screenshot 2024-07-29 at 13 55 38" src="https://github.com/user-attachments/assets/e3dccb79-b661-4850-bd4b-4bfbe36633c1">

2024-07-29 10:45 UTC, cristian-scarisoreanu commented
- The title should usually be **Hotfix / [Name of the issue]**

- You should add the issue URL to the PR

- You should follow the PR template:

![image](https://github.com/user-attachments/assets/2ec566be-ee70-4f28-a961-43b7171ea11f)

- Maybe you could try to screenshot only the terminal, not the whole screen

2024-07-29 10:52 UTC, cristian-scarisoreanu commented
Fix rubocop warnings.

2024-07-29 10:53 UTC, cristian-scarisoreanu requested changes

2024-07-29 10:53 UTC, cristian-scarisoreanu commented on Gemfile.lock
> +    actioncable (6.1.7.8)
There is no need to modify `Gemfile.lock`. You can remove it from the PR. Next time, please ensure this file is not in the committed files.

2024-07-29 12:34 UTC, cristian-scarisoreanu requested changes

2024-07-29 12:34 UTC, cristian-scarisoreanu commented on spec/spec_helper.rb
> -  if config.files_to_run.one?
Why did you remove this?

2024-07-29 12:37 UTC, andreidumitru11 commented on spec/spec_helper.rb
> -  if config.files_to_run.one?
When I ran "rubocop" , it pointed out that the if statement it's empty.

2024-07-29 12:41 UTC, cristian-scarisoreanu commented on spec/spec_helper.rb
> -  if config.files_to_run.one?
Let's only modify the necessary files to solve the issue and revert this file to its original state. Ensure that rubocop does not add warnings to our modifications, not the entire codebase.

2024-07-30 10:37 UTC, cristian-scarisoreanu approved these changes

2024-08-01 11:29 UTC, merged